---
# tasks file for ssh-safety

# continue from https://plusbryan.com/my-first-5-minutes-on-a-server-or-essential-security-for-linux-servers
# and https://www.cyberciti.biz/tips/linux-unix-bsd-openssh-server-best-practices.html
- fail:
    msg: "e-mail notifications need an e-mail address"
    when: SSH_LOG_EMAIL is undefined

- name: install brute force lock
  apt:
    name: fail2ban
    # install_recommends: yes
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  become: yes
  when: ansible_pkg_mgr == 'apt'

- name: set sshd_config to refuse root logins
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#+\s*PermitRootLogin .*$'
    line: 'PermitRootLogin no'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  become: yes
  notify: restart ssh service

- name: set sshd_config to refuse password logins
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#+\s*PasswordAuthentication .*$'
    line: 'PasswordAuthentication no'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  become: yes
  notify: restart ssh service

- name: set sshd_config to refuse empty password logins
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#+\s*PermitEmptyPasswords .*$'
    line: 'PermitEmptyPasswords no'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  become: yes
  notify: restart ssh service

- name: set sshd_config to use protocol 2 wich is more secure
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#+\s*Protocol 2$'
    line: 'Protocol 2'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  become: yes
  notify: restart ssh service

- name: set sshd_config to refuse hostbased auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#+\s*HostbasedAuthentication .*$'
    line: 'HostbasedAuthentication no'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  become: yes
  notify: restart ssh service

- name: enable periodic updates
  template:
    src: 10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    backup: yes
  become: yes

- name: install logwatch e-mail reporter
  apt:
    name: logwatch
    # install_recommends: yes
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  become: yes
  when: ansible_pkg_mgr == 'apt'

- name: enable logwatch e-mail reports
  template:
    src: 00logwatch.j2
    dest: /etc/cron.daily/00logwatch
    owner: root
    group: root
    backup: yes
  become: yes
